# Generated by Django 5.0.2 on 2024-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.AlterField(
            model_name='officer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates wether this users should have all permissions without explicitly assigning them', verbose_name='superuser status'),
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('police_number', 'national_id')},
        ),
    ]
