# Generated by Django 5.0.3 on 2024-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_filemetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileMetadata',
            new_name='AccidentFiles',
        ),
    ]
