# Generated by Django 5.0.3 on 2024-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_rename_filemetadata_accidentfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentfiles',
            name='abstract',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
