# Generated by Django 5.0.3 on 2024-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_accidentfiles_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
