# Generated by Django 5.0.3 on 2024-03-27 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergencyreport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
