# Generated by Django 5.0.3 on 2024-03-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergencyreport_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='unique_id',
        ),
    ]
