# Generated by Django 5.0.3 on 2024-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_remove_emergencyreport_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('witness_name1', models.CharField(blank=True, max_length=255)),
                ('witness_phone1', models.CharField(blank=True, max_length=20)),
                ('witness_name2', models.CharField(blank=True, max_length=255)),
                ('witness_phone2', models.CharField(blank=True, max_length=20)),
                ('evidence_description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/crime_photos/')),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
