# Generated by Django 5.0.3 on 2024-03-30 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_crimereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
