# Generated by Django 5.0.3 on 2024-04-10 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_crimereport_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_file_no', models.CharField(max_length=50, unique=True)),
                ('odpp_case_no', models.CharField(max_length=50, unique=True)),
                ('odpp_station', models.CharField(max_length=100)),
                ('police_case_no', models.CharField(max_length=50, unique=True)),
                ('ob_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='OB number must be digits only', regex='^\\d+$')])),
                ('date_drafted', models.DateField(auto_now_add=True)),
                ('christian_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be digits only', regex='^\\d+$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('charge', models.TextField()),
                ('particulars_of_offense', models.TextField()),
                ('date_of_arrest', models.DateField(blank=True, null=True)),
                ('is_warranted', models.CharField(choices=[('with', 'With'), ('without', 'Without')], max_length=10)),
                ('apprehension_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('complaint_address', models.TextField()),
                ('sentence', models.TextField(blank=True)),
                ('prosecutor', models.CharField(max_length=100)),
                ('witnesses', models.ManyToManyField(blank=True, to='emergency.witness')),
            ],
        ),
    ]
