# Generated by Django 5.0.3 on 2024-04-11 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0008_witness_chargesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('to_facility', models.CharField(max_length=255)),
                ('person_examined_name', models.CharField(max_length=255)),
                ('person_examined_address', models.CharField(max_length=255)),
                ('alleged_offense_date', models.DateField(blank=True, null=True)),
                ('alleged_offense_details', models.TextField(blank=True)),
                ('officer_commanding_station_name', models.CharField(max_length=255)),
                ('officer_commanding_station_signature', models.CharField(max_length=255)),
                ('medical_officer_reference', models.CharField(max_length=255)),
                ('clothing_state', models.CharField(max_length=255)),
                ('general_medical_history', models.TextField()),
                ('general_physical_exam', models.TextField()),
                ('injuries_details', models.TextField()),
                ('injuries_age', models.CharField(max_length=255)),
                ('weapon_type', models.CharField(blank=True, max_length=255)),
                ('prior_treatment', models.CharField(blank=True, max_length=255)),
                ('clinical_results', models.TextField()),
                ('medical_officer_name', models.CharField(max_length=255)),
                ('medical_officer_date', models.DateField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
